In [27]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [28]:
df = df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis = 'columns')
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [29]:
target = df.Survived
inputs = df.drop('Survived', axis = 'columns')

In [30]:
dummies = pd.get_dummies(inputs.Sex, dtype = int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [31]:
inputs = pd.concat([inputs, dummies], axis = 'columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [32]:
inputs.columns

Index(['Pclass', 'Sex', 'Age', 'Fare', 'female', 'male'], dtype='object')

In [33]:
inputs = inputs.drop('Sex', axis = 'columns')
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [34]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [35]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [38]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1
6       1  54.000000  51.8625       0     1
7       3   2.000000  21.0750       0     1
8       3  27.000000  11.1333       1     0
9       2  14.000000  30.0708       1     0

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.2)

In [40]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [41]:
model.fit(X_train, y_train)

GaussianNB()

In [43]:
model.predict(X_test)

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1])

In [44]:
model.score(X_test, y_test)

0.776536312849162

In [45]:
X_test[:10]

     Pclass   Age      Fare  female  male
550       1  17.0  110.8833       0     1
461       3  34.0    8.0500       0     1
234       2  24.0   10.5000       0     1
617       3  26.0   16.1000       1     0
200       3  28.0    9.5000       0     1
720       2   6.0   33.0000       1     0
512       1  36.0   26.2875       0     1
858       3  24.0   19.2583       1     0
210       3  24.0    7.0500       0     1
268       1  58.0  153.4625       1     0

In [47]:
y_test[:10]

550    1
461    0
234    0
617    0
200    0
720    1
512    1
858    1
210    0
268    1
Name: Survived, dtype: int64

In [48]:
model.predict(X_test[:10])

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1])

In [49]:
model.predict_proba(X_test)

array([[2.35944070e-01, 7.64055930e-01],
       [9.91334448e-01, 8.66555210e-03],
       [9.78511476e-01, 2.14885245e-02],
       [6.80977759e-02, 9.31902224e-01],
       [9.90961702e-01, 9.03829761e-03],
       [1.71647454e-02, 9.82835255e-01],
       [9.23748757e-01, 7.62512429e-02],
       [6.59154610e-02, 9.34084539e-01],
       [9.90335364e-01, 9.66463574e-03],
       [5.03617775e-06, 9.99994964e-01],
       [7.94616776e-01, 2.05383224e-01],
       [9.78112408e-01, 2.18875917e-02],
       [6.94551162e-02, 9.30544884e-01],
       [2.17803389e-04, 9.99782197e-01],
       [8.97736085e-01, 1.02263915e-01],
       [9.79656203e-01, 2.03437968e-02],
       [7.29014253e-02, 9.27098575e-01],
       [2.92409002e-02, 9.70759100e-01],
       [9.91420034e-01, 8.57996616e-03],
       [9.91043398e-01, 8.95660246e-03],
       [1.45777462e-02, 9.85422254e-01],
       [3.22771806e-02, 9.67722819e-01],
       [9.91401978e-01, 8.59802161e-03],
       [7.14938581e-02, 9.28506142e-01],
       [1.59776906e-02, 9.84022309e-01],
       [9.20847956e-01, 7.91520445e-02],
       [9.80315227e-01, 1.96847732e-02],
       [9.17630921e-01, 8.23690788e-02],
       [9.89905069e-01, 1.00949312e-02],
       [9.05262984e-01, 9.47370160e-02],
       [3.10594982e-02, 9.68940502e-01],
       [6.94597924e-02, 9.30540208e-01],
       [5.88153360e-02, 9.41184664e-01],
       [9.90817162e-01, 9.18283767e-03],
       [9.23655765e-01, 7.63442353e-02],
       [8.64473711e-01, 1.35526289e-01],
       [6.23018181e-02, 9.37698182e-01],
       [9.90941374e-01, 9.05862623e-03],
       [1.02441973e-05, 9.99989756e-01],
       [9.91165147e-01, 8.83485257e-03],
       [9.19411810e-01, 8.05881902e-02],
       [9.14045718e-01, 8.59542817e-02],
       [9.78356820e-01, 2.16431801e-02],
       [9.87343595e-01, 1.26564051e-02],
       [9.20870696e-01, 7.91293041e-02],
       [7.05504531e-02, 9.29449547e-01],
       [9.06930976e-01, 9.30690242e-02],
       [1.49594766e-03, 9.98504052e-01],
       [5.31636394e-06, 9.99994684e-01],
       [9.89740275e-01, 1.02597245e-02],
       [3.35618167e-02, 9.66438183e-01],
       [5.32812241e-02, 9.46718776e-01],
       [9.88824669e-01, 1.11753306e-02],
       [9.89870173e-01, 1.01298275e-02],
       [6.96807120e-02, 9.30319288e-01],
       [7.72778977e-03, 9.92272210e-01],
       [9.91145269e-01, 8.85473095e-03],
       [9.90519225e-01, 9.48077466e-03],
       [7.08823212e-02, 9.29117679e-01],
       [3.34524887e-02, 9.66547511e-01],
       [4.88724850e-03, 9.95112751e-01],
       [4.32147997e-02, 9.56785200e-01],
       [6.95698032e-02, 9.30430197e-01],
       [9.90791977e-01, 9.20802345e-03],
       [9.51785081e-04, 9.99048215e-01],
       [9.89230644e-01, 1.07693556e-02],
       [9.91057203e-01, 8.94279748e-03],
       [3.89915514e-05, 9.99961008e-01],
       [7.14770340e-01, 2.85229660e-01],
       [5.89346882e-02, 9.41065312e-01],
       [9.59801269e-01, 4.01987314e-02],
       [9.80116712e-01, 1.98832882e-02],
       [4.93003838e-03, 9.95069962e-01],
       [9.91242670e-01, 8.75733029e-03],
       [9.90227566e-01, 9.77243407e-03],
       [3.21465667e-02, 9.67853433e-01],
       [9.88774480e-01, 1.12255204e-02],
       [3.79038930e-02, 9.62096107e-01],
       [9.83775734e-01, 1.62242664e-02],
       [9.91042116e-01, 8.95788380e-03],
       [9.91015563e-01, 8.98443664e-03],
       [1.75258017e-03, 9.98247420e-01],
       [9.85262013e-01, 1.47379866e-02],
       [9.88744197e-01, 1.12558028e-02],
       [3.15884306e-02, 9.68411569e-01],
       [9.91043398e-01, 8.95660246e-03],
       [9.78687660e-01, 2.13123402e-02],
       [9.85449031e-01, 1.45509691e-02],
       [9.91037703e-01, 8.96229698e-03],
       [9.91057203e-01, 8.94279748e-03],
       [6.94597924e-02, 9.30540208e-01],
       [2.52498722e-03, 9.97475013e-01],
       [9.80095352e-01, 1.99046481e-02],
       [9.80210543e-01, 1.97894571e-02],
       [3.17320145e-02, 9.68267986e-01],
       [7.34582588e-02, 9.26541741e-01],
       [9.91326192e-01, 8.67380846e-03],
       [8.64455058e-01, 1.35544942e-01],
       [9.73730326e-01, 2.62696745e-02],
       [9.77640717e-01, 2.23592831e-02],
       [9.90994733e-01, 9.00526669e-03],
       [7.80738161e-03, 9.92192618e-01],
       [9.91016839e-01, 8.98316078e-03],
       [9.78970604e-01, 2.10293964e-02],
       [7.24736899e-01, 2.75263101e-01],
       [9.91060266e-01, 8.93973392e-03],
       [9.03116664e-01, 9.68833356e-02],
       [2.81967822e-02, 9.71803218e-01],
       [6.94597924e-02, 9.30540208e-01],
       [6.05210498e-01, 3.94789502e-01],
       [9.91358539e-01, 8.64146053e-03],
       [9.91221818e-01, 8.77818216e-03],
       [9.91057203e-01, 8.94279748e-03],
       [3.54113763e-02, 9.64588624e-01],
       [9.89263257e-01, 1.07367427e-02],
       [6.38662288e-03, 9.93613377e-01],
       [9.89466946e-01, 1.05330542e-02],
       [9.60104748e-01, 3.98952515e-02],
       [9.90728751e-01, 9.27124904e-03],
       [5.83062212e-02, 9.41693779e-01],
       [9.90527515e-01, 9.47248470e-03],
       [9.91042116e-01, 8.95788380e-03],
       [2.66990421e-01, 7.33009579e-01],
       [9.90082069e-01, 9.91793127e-03],
       [9.89146684e-01, 1.08533165e-02],
       [2.43987734e-02, 9.75601227e-01],
       [9.76646593e-01, 2.33534074e-02],
       [3.25551894e-02, 9.67444811e-01],
       [9.87677171e-01, 1.23228288e-02],
       [6.95076928e-02, 9.30492307e-01],
       [3.51180215e-05, 9.99964882e-01],
       [9.91057203e-01, 8.94279748e-03],
       [9.17698807e-01, 8.23011932e-02],
       [8.09770207e-04, 9.99190230e-01],
       [6.99401118e-02, 9.30059888e-01],
       [9.91376234e-01, 8.62376567e-03],
       [9.89393759e-01, 1.06062412e-02],
       [9.89776508e-01, 1.02234923e-02],
       [9.91042116e-01, 8.95788380e-03],
       [9.76489612e-01, 2.35103881e-02],
       [9.23538120e-01, 7.64618805e-02],
       [5.40410675e-02, 9.45958932e-01],
       [9.51285096e-01, 4.87149042e-02],
       [9.91049527e-01, 8.95047294e-03],
       [9.90961702e-01, 9.03829761e-03],
       [9.20733659e-01, 7.92663406e-02],
       [8.62051401e-01, 1.37948599e-01],
       [6.75316973e-02, 9.32468303e-01],
       [3.12762122e-02, 9.68723788e-01],
       [6.96807120e-02, 9.30319288e-01],
       [9.83546132e-01, 1.64538675e-02],
       [6.24400152e-02, 9.37559985e-01],
       [9.80878514e-01, 1.91214863e-02],
       [3.21557501e-02, 9.67844250e-01],
       [9.23090907e-01, 7.69090932e-02],
       [6.13103268e-02, 9.38689673e-01],
       [9.91059261e-01, 8.94073894e-03],
       [9.19965896e-01, 8.00341043e-02],
       [9.91042116e-01, 8.95788380e-03],
       [6.99671949e-02, 9.30032805e-01],
       [9.21893389e-01, 7.81066107e-02],
       [9.91014189e-01, 8.98581073e-03],
       [9.91049527e-01, 8.95047294e-03],
       [9.91269531e-01, 8.73046872e-03],
       [1.97006837e-04, 9.99802993e-01],
       [9.17359977e-01, 8.26400232e-02],
       [9.20733659e-01, 7.92663406e-02],
       [3.12650158e-02, 9.68734984e-01],
       [9.91235190e-01, 8.76480996e-03],
       [9.91582926e-01, 8.41707396e-03],
       [9.79904871e-01, 2.00951286e-02],
       [9.78312713e-01, 2.16872868e-02],
       [9.91088290e-01, 8.91171027e-03],
       [7.08954831e-02, 9.29104517e-01],
       [1.41751783e-03, 9.98582482e-01],
       [9.14964318e-01, 8.50356816e-02],
       [9.90058388e-01, 9.94161175e-03],
       [6.94597924e-02, 9.30540208e-01],
       [3.70313258e-02, 9.62968674e-01]])