In [2]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [15]:
df = pd.read_csv("hr_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [16]:
left = df[df['left'] == 1]
retained = df[df['left'] == 0]

In [19]:
df.groupby('left').mean(numeric_only = True)

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years
left,,,,,,,
0,0.666810,0.715473,3.786664,199.060203,3.380032,0.175009,0.026251
1,0.440098,0.718113,3.855503,207.419210,3.876505,0.047326,0.005321

In [21]:
# The numeric factors that impact whether an employee leaves a firm are: satisfaction_level, average_monthly_hours, and promotion_last_5years

In [24]:
newdf = df[['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 'salary']]

In [26]:
dummies = pd.get_dummies(df['salary'], dtype = int)
dummies

       high  low  medium
0         0    1       0
1         0    0       1
2         0    0       1
3         0    1       0
4         0    1       0
...     ...  ...     ...
14994     0    1       0
14995     0    1       0
14996     0    1       0
14997     0    1       0
14998     0    1       0

[14999 rows x 3 columns]

In [30]:
merged = pd.concat([newdf, dummies], axis = 'columns') 
merged.head()

,satisfaction_level,average_montly_hours,promotion_last_5years,salary,high,low,medium
0,0.38,157,0,low,0,1,0
1,0.80,262,0,medium,0,0,1
2,0.11,272,0,medium,0,0,1
3,0.72,223,0,low,0,1,0
4,0.37,159,0,low,0,1,0

In [31]:
finaldf = merged.drop(['salary'], axis = 'columns')

In [32]:
finaldf.head()

,satisfaction_level,average_montly_hours,promotion_last_5years,high,low,medium
0,0.38,157,0,0,1,0
1,0.80,262,0,0,0,1
2,0.11,272,0,0,0,1
3,0.72,223,0,0,1,0
4,0.37,159,0,0,1,0

In [37]:
X = finaldf
y = df['left']

In [38]:
X

,satisfaction_level,average_montly_hours,promotion_last_5years,high,low,medium
0,0.38,157,0,0,1,0
1,0.80,262,0,0,0,1
2,0.11,272,0,0,0,1
3,0.72,223,0,0,1,0
4,0.37,159,0,0,1,0
...,...,...,...,...,...,...
14994,0.40,151,0,0,1,0
14995,0.37,160,0,0,1,0
14996,0.37,143,0,0,1,0
14997,0.11,280,0,0,1,0
14998,0.37,158,0,0,1,0

In [39]:
y

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: left, Length: 14999, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

In [44]:
X_test

,satisfaction_level,average_montly_hours,promotion_last_5years,high,low,medium
4834,0.76,204,0,0,1,0
12585,0.40,139,0,0,1,0
3162,0.64,246,0,0,1,0
5199,0.34,283,0,1,0,0
8956,0.87,144,0,0,0,1
...,...,...,...,...,...,...
5179,0.34,178,0,0,1,0
3771,0.80,246,0,0,0,1
10419,0.63,162,0,0,1,0
5237,0.66,141,0,0,0,1
6729,0.87,197,0,0,1,0

In [45]:
X_train

,satisfaction_level,average_montly_hours,promotion_last_5years,high,low,medium
2771,0.98,285,0,0,1,0
3675,0.64,165,0,0,1,0
3681,0.19,152,0,0,1,0
5438,0.93,225,0,0,0,1
1034,0.10,266,0,0,1,0
...,...,...,...,...,...,...
8927,0.91,210,0,0,0,1
4475,0.67,262,0,0,0,1
9153,0.41,236,0,0,0,1
8659,0.67,266,0,0,0,1
7030,0.71,135,0,0,1,0

In [46]:
from sklearn.linear_model import LogisticRegression

In [47]:
lreg = LogisticRegression()

In [48]:
lreg.fit(X_train, y_train)

LogisticRegression()

In [49]:
lreg.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], shape=(1500,))

In [51]:
lreg.score(X_test, y_test)

0.774